# Generated by Django 5.1.4 on 2025-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
