# Generated by Django 5.1.4 on 2025-01-26 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0003_valorobra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorobra',
            name='descricao',
        ),
        migrations.AddField(
            model_name='valorobra',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='valorobra',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_obra', to='obras.obra'),
        ),
        migrations.CreateModel(
            name='ValorAdicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_adicionados', to='obras.obra')),
            ],
        ),
    ]
