# Generated by Django 5.1.4 on 2025-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0004_remove_valorobra_descricao_valorobra_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoradicionado',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
