# Generated by Django 5.1.4 on 2025-02-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0005_valoradicionado_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoradicionado',
            name='forma_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('credito', 'Cartão de Crédito'), ('debito', 'Cartão de Débito')], default='dinheiro', max_length=10),
            preserve_default=False,
        ),
    ]
