# Generated by Django 5.1.4 on 2025-04-23 03:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0006_valoradicionado_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor_diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_adicionado', models.DateTimeField(default=django.utils.timezone.now)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='obras.obra')),
            ],
        ),
    ]
